version: "3"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - catalram
    networks:
      - backend

  app:
    build: .
    restart: always
    ports:
      - 3000:3000
    links:
      - mongo
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  catalram:
