version: "3"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - catalram
  app:
    build: .
    ports:
      - 3000:3000
    links:
      - mongo

volumes:
  catalram: {}
